### ISSUE TITLE
Stuck on Chrome failed to start :/

### ISSUE THREAD

**Issue by razorcrackers** [lfasmpao/box.com-downloader#1]
Running on Ubuntu 16.04 

`Box.com PDF Downloader by @lfasmpao
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 44, in main
    box_object = Scraper(args.url, args.driver_location, args.use_x11, args.wait_time)
  File "/root/box.com-downloader/scraper.py", line 76, in __init__
    self.driver_obj = webdriver.Chrome(self.driver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __ini                         t__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __in                         it__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in star                         t_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in exec                         ute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in c                         heck_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abn                         ormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-                         127-generic x86_64)

root@guest:~/box.com-downloader# selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
`

**Comment by lfasmpao** [comment]
Hello @razorcrackers, it seems you are using Python 2.7, this application is only tested on Python 3.6. Please let me know if the same problem occurred after you did an update. Thanks!

**Comment by razorcrackers** [comment]
Oh right! Haha forgot to change to 3.6
Thanks!

**Comment by lfasmpao** [comment]
@razorcrackers, I've fixed the crash when you run the app as root, just clone the master branch again. 🎉

**Comment by razorcrackers** [comment]
Changed to 3.6. Got another one. Maybe I was not able to install it well since I'm new to Chrome Driver and Selenium. :(
`Box.com PDF Downloader by @lfasmpao
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 44, in main
    box_object = Scraper(args.url, args.driver_location, args.use_x11, args.wait_time)
  File "/root/box.com-downloader/scraper.py", line 76, in __init__
    self.driver_obj = webdriver.Chrome(self.driver_location, chrome_options=chrome_options)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 67, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-127-generic x86_64)
`

**Comment by razorcrackers** [comment]
Okay. Thanks. :smile: Take 2 hehe

**Comment by razorcrackers** [comment]
Added x11 but still got nothing  
`root@guest:~/box.com-downloader# python main.py https://app.box.com/s/hs5de51wub2htrcl0hxn1wir4zpmf3wj --driver-path /usr/local/bin/chromedriver --use-x11
=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Box.com PDF Downloader by @lfasmpao
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 44, in main
    box_object = Scraper(args.url, args.driver_location, args.use_x11, args.wait_time)
  File "/root/box.com-downloader/scraper.py", line 78, in __init__
    self.driver_obj = webdriver.Chrome(self.driver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-127-generic x86_64)
`

**Comment by lfasmpao** [comment]
Probably there's a problem with your chrome installation. Use the latest chrome stable and chromedriver

**Comment by razorcrackers** [comment]
Probably. Are you using Ubuntu? What are your commands in installing chromedriver and chrome stable?Maybe mine was wrong. Thanks!

**Comment by razorcrackers** [comment]
Got it already! Clean installation :smile: Thanks! ^_^

**Comment by razorcrackers** [comment]
For those who are having a hard time running the app, this [link](https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5#file-start-chrome-sh-L9) can help.
